version: '3'
services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ../mobile/dist:/usr/share/nginx/html/mobile
      - ../backoffice/dist:/usr/share/nginx/html/backoffice
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - db_bridge
      
networks:
  db_bridge:
    external: true